// src/components/sections/ExperienceSection.tsx
'use client'

import { motion } from 'framer-motion'

import { Badge } from '@/components/ui/badge'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { experience } from '@/data'

export function ExperienceSection() {
  return (
    <section id="experience" className="py-20 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ ease: 'easeInOut', duration: 0.5 }}
          className="text-center mb-16"
        >
          <h2 className="text-3xl sm:text-4xl mb-4">Experience</h2>
          <p className="text-xl text-muted-foreground">
            My professional journey and career highlights
          </p>
        </motion.div>

        <div className="space-y-8">
          {experience.map((exp, index) => (
            <motion.div
              key={exp.company}
              initial={{ opacity: 0, x: index % 2 === 0 ? -30 : 30 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ ease: 'easeInOut', duration: 0.5 }}
            >
              <Card>
                <CardHeader>
                  <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2">
                    <div>
                      <CardTitle className="leading-6">{exp.title}</CardTitle>
                      <CardDescription className="text-primary">{exp.company}</CardDescription>
                    </div>
                    <Badge variant="outline">{exp.period}</Badge>
                  </div>
                </CardHeader>
                <CardContent>
                  <p className="text-muted-foreground">{exp.description}</p>
                </CardContent>
              </Card>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  )
}

// src/components/Sections/ExperienceSection.vue
<script setup lang="ts">
import { experience } from '@/data'
import Card from '../ui/card/Card.vue'
import CardHeader from '../ui/card/CardHeader.vue'
import CardTitle from '../ui/card/CardTitle.vue'
import CardDescription from '../ui/card/CardDescription.vue'
import Badge from '../ui/badge/Badge.vue'
import CardContent from '../ui/card/CardContent.vue'
</script>
<template>
  <section id="experience" class="py-20 px-4 sm:px-6 lg:px-8">
    <div class="max-w-4xl mx-auto">
      <div
        :initial="{ opacity: 0, y: 30 }"
        :enter="{ opacity: 1, y: 0, animation: 'ease-in-out', animationDuration: '500ms' }"
        class="text-center mb-16"
      >
        <h2 class="text-3xl sm:text-4xl mb-4">Experience</h2>
        <p class="text-xl text-muted-foreground">My professional journey and career highlights</p>
      </div>

      <div class="space-y-8">
        <div
          v-for="(exp, index) in experience"
          :key="index"
          :initial="{ opacity: 0, x: index % 2 === 0 ? -30 : 30 }"
          :enter="{ opacity: 1, x: 0, animation: 'ease-in-out', animationDuration: '500ms' }"
        >
          <Card>
            <CardHeader>
              <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2">
                <div>
                  <CardTitle class='leading-6'>{{ exp.title }}</CardTitle>
                  <CardDescription class="text-primary">{{ exp.company }}</CardDescription>
                </div>
                <Badge variant="outline">{{ exp.period }}</Badge>
              </div>
            </CardHeader>
            <CardContent>
              <p class="text-muted-foreground">{{ exp.description }}</p>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  </section>
</template>
