// src/components/layout/Footer.tsx
import { Code2, Github, Linkedin, Mail } from 'lucide-react'

import { Button } from '@/components/ui/button'
import { Separator } from '@/components/ui/separator'
import { allSocials } from '@/data'

export function Footer() {
  return (
    <footer className="py-8 px-4 sm:px-6 lg:px-8 border-t border-border">
      <div className="max-w-6xl mx-auto">
        <Separator className="mb-8" />
        <div className="flex flex-col sm:flex-row justify-between items-center gap-4">
          <div className="flex items-center space-x-2">
            <Code2 className="h-6 w-6 text-primary" />
            <span>© 2025 Ali Barznji. All rights reserved.</span>
          </div>
          <div className="flex space-x-4">
            <Button variant="ghost" size="icon" asChild>
              <a href={allSocials.github.link} target="_blank" rel="noopener noreferrer">
                <Github className="h-5 w-5" />
              </a>
            </Button>
            <Button variant="ghost" size="icon" asChild>
              <a href={allSocials.linkedin.link} target="_blank" rel="noopener noreferrer">
                <Linkedin className="h-5 w-5" />
              </a>
            </Button>
            <Button variant="ghost" size="icon" asChild>
              <a href={`mailto:${allSocials.email.link}`}>
                <Mail className="h-5 w-5" />
              </a>
            </Button>
          </div>
        </div>
      </div>
    </footer>
  )
}

// app/layouts/Footer.vue
<script setup lang="ts">
import GithubIcon from "~/assets/icons/github-icon.vue";
import LinkedinIcon from "~/assets/icons/linkedin-icon.vue";
import LogoFilledIcon from "~/assets/icons/logo-filled-icon.vue";
import MailIcon from "~/assets/icons/mail-icon.vue";
const socialLinks = [
  {
    icon: GithubIcon,
    name: "github",
    path: "https://github.com/ali559",
  },
  {
    icon: LinkedinIcon,
    name: "linkedin",
    path: "https://www.linkedin.com/in/ali-barznji-36b664325/",
  },
  {
    icon: MailIcon,
    name: "Email",
    path: "mailto:biz@alibarznji.dev",
  },
];
</script>

<template>
  <footer class="py-8 border-t-1 border-secondary">
    <div class="max-w-[1070px] mx-auto px-4">
      <div
        class="w-full flex flex-col gap-16 sm:flex-row sm:justify-between sm:gap-0"
      >
        <!-- First Row/Column -->
        <div>
          <div class="flex items-center gap-2">
            <button class="flex items-center gap-1 bg-transparent">
              <LogoFilledIcon class="w-4 h-4" />
              <h1 class="text-base font-bold text-white">Ali</h1>
            </button>
            <NuxtLink
              to="mailto:biz@alibarznji.dev"
              class="text-secondary hover:text-primary transition-colors duration-300 ease-in-out"
            >
              biz@alibarznji.dev
            </NuxtLink>
          </div>
          <p class="text-white mt-4">
            Fullstack Engineer and a Programming Enthusiast
          </p>
        </div>

        <!-- Second Row/Column -->
        <div>
          <h3 class="text-white font-medium text-2xl">Media</h3>
          <div class="flex items-center gap-2 mt-2">
            <NuxtLink
              v-for="(link, index) in socialLinks"
              :key="index"
              target="_blank"
              :to="link.path"
              class="text-secondary hover:text-primary transition-colors duration-300 ease-in-out"
            >
              <component :is="link.icon" class="w-8 h-8" />
            </NuxtLink>
          </div>
        </div>
      </div>
      <p class="text-secondary text-center w-full mt-16">
        © Copyright 2025. Made by Ali
      </p>
    </div>
  </footer>
</template>
